### PR TITLE
Update dependencies and fix related issues, create Github Workflow for Rperform

### LINKED ISSUE #44: An error message popped up when using
Hi, @analyticalmonk . I got an error message when I try to reproduce examples at the README page. I forked your _stringr_ repo and committed twice with some small changes in test-join.r. Then I tried plot_metrics and I got an error message, Here is the console log:
```
> getwd()
[1] "C:/Users/65112/Documents/stringr"
> plot_metrics(test_path = "tests/testthat/test-join.r", metric = "time", num_commits = 2, save_data = FALSE, save_plots = FALSE)
Error in base::substr(commit_val@summary, start = 1, stop = 15) : 
  trying to get slot "summary" from an object (class "git_commit") that is not an S4 object 
```
There is no error message when num_commits = 0 and no plot comes out.
Could you help me with this problem? Thank you in advance.

### LINKED ISSUE #45: Support git2r's switch from S4 to S3 objects
Bug: https://github.com/analyticalmonk/Rperform/issues/44

Reference: https://github.com/ropensci/git2r/issues/312

### PR DESCRIPTION
**Pull request by EngineerDanny**
This PR fixes most of the issues raised.

1. Indentation inconsistency in the R files have been fixed by using R studio's built-in indentation. [(1)](https://github.com/EngineerDanny/Rperform/pull/2#discussion_r904718686)
2. Various binary files and directories have been added to the **.gitignore** file. [(2)](https://github.com/EngineerDanny/Rperform/pull/2#issuecomment-1164099213)
3. [animint](https://github.com/tdhock/animint) package has been updated to  [animint2](https://github.com/tdhock/animint2) which comes with improved features and better syntax.
4. [git2r](https://github.com/ropensci/git2r) package has also been updated to support the latest features and improvements `git2r (>= 0.30.1)`
5. Named reference approach has been adopted to reference list members by names instead of numeric indexes. [(3)](https://github.com/EngineerDanny/Rperform/pull/3#discussion_r904711183)
6. A Github CI Worflow has been created for setting up Rperform and running R CMD Check by using [r-lib/actions](https://github.com/r-lib/actions)

R CMD Check Runs successfully ✅

This **PR** closes #44 and fixes #45

### CODE REVIEW

**Review by analyticalmonk — APPROVED** [review]
The changes look good.

We should also update the README to incorporate your findings regarding testing the `stringr` package with Rperform. We can do that in a separate PR.

**Comment by EngineerDanny** [comment]
Sure. 
I will update that and submit another PR.

**Comment by analyticalmonk** [comment]
Amazing work @EngineerDanny! :tada: 
cc: @tdhock

**Comment by EngineerDanny** [comment]
Great Akash

**Pull request merged**
